### ISSUE TITLE
There is no iphoneOS framework in the branch swift-3.0

### ISSUE THREAD

**Issue by lztetreault** [TakeScoop/SwiftyRSA#35]
The only framework that shows up to add as an embedded binary is for tvOS

**Comment by ldiqual** [comment]
@lztetreault I just pushed `0.5.0` on cocoapods and you can checkout the source code on `master`. It contains all 3 schemes (iOS, tvOS, watchOS) and all build + tests passed locally on my machine. Let me know if it works for you.

**Comment by lztetreault** [comment]
Hi, thanks for the update @ldiqual. The only embedded binaries that show up for SwiftyRSA now are 
* SwiftyRSA.framework tvOS
* SwiftyRSATests.xctest iOS
I still can't add it my project without it complaining.

**Comment by ldiqual** [comment]
@lztetreault How are you integrating SwiftyRSA into your project?

**Comment by lztetreault** [comment]
Sorry for the very late response but I was manually adding it by adding your repo as a submodule and then dragging it into Xcode

**Comment by ldiqual** [comment]
@lztetreault Can you try again with the `master` branch and get back to me? We only officially support cocoapods and carthage as integration methods, just so you know.
